### ISSUE TITLE
[Errno 111] connection refused

### ISSUE THREAD

**Issue by km1994** [Babylonpartners/rgat#2]
Exception: URL fetch 
 failure on https://www.dropbox.com/s/fkvgvkygo2gf28k/aifb_stripped.nt.gz?dl=1: None -- [Errno 111] connection refused

**Comment by dbusbridge** [comment]
Hi km1994,

This error could be caused by as lot of different things relating to your network setup. You can circumvent it by manually downloading the data and placing it in the correct location - the script will then run locally.

Specifically, for AIFB, make a folder `$HOME/.keras/datasets/AIFB`

and then download the file manually, for example:

`$ wget htps://www.dropbox.com/s/fkvgvkygo2gf28k/aifb_stripped.nt.gz?dl=1`

when inside the folder above. Similarly for MUTAG, create the folder `$HOME/.keras/datasets/MUTAG` and use the URL `https://www.dropbox.com/s/qy8j3p8eacvm4ir/mutag_stripped.nt.gz?dl=1`

Hope this helps!

Cheers, Dan
